# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGeneral',
            fields=[
                ('DeviceID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Industry', models.CharField(max_length=30)),
                ('ReleaseDate', models.DateField()),
                ('Description', models.TextField()),
                ('Manufacturer', models.TextField()),
                ('PictureUrl', models.URLField()),
                ('Availabilty', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Interactivity', models.TextField()),
                ('AppName', models.TextField()),
                ('FirmVersion', models.TextField()),
                ('DateTested', models.DateField()),
                ('OS', models.TextField()),
                ('ComunicationMethod', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTrafficPattern',
            fields=[
                ('DeviceID', models.IntegerField(primary_key=True, serialize=False)),
                ('SleepTime', models.IntegerField()),
                ('ActiveVolume', models.IntegerField()),
                ('AvgPacketSize', models.IntegerField()),
                ('MeanRate', models.IntegerField()),
                ('PeakRate', models.IntegerField()),
                ('ActiveTime', models.IntegerField()),
                ('NumServersComm', models.IntegerField()),
                ('NumProtocols', models.IntegerField()),
                ('UniqueDNSReq', models.IntegerField()),
                ('DNSInterval', models.IntegerField()),
                ('NTPInterval', models.IntegerField()),
                ('PortsOpen', models.TextField()),
                ('PortComm', models.TextField()),
                ('EncryptionProtocol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('ExploitID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeviceID', models.IntegerField()),
                ('ExploitInfoID', models.IntegerField()),
                ('ExploitDetail', models.TextField()),
                ('Script', models.TextField()),
                ('SamplePCAP', models.TextField()),
                ('Characteristic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExploitInfo',
            fields=[
                ('ExploitInfoID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExploitName', models.TextField()),
                ('ExploitInfo', models.TextField()),
            ],
        ),
    ]
